version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: socket.io
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
    - 4.0.1
  - dependency-name: open
    versions:
    - 8.0.1
    - 8.0.2
