ignore:
  - 'src/router.*'
  - 'src/index.*'
  - 'nino.koei.js'

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  branches: !gh-pages

codecov:
  bot: codecovbot

coverage:
  status:
    project:
      default: off
    patch:
      default: off
