[mysql]
host = 'localhost'
user = 'root'
password = ''
database = 'toy-box'

[sign]
'出入库' = 0
# 圆钢、方钢、模套、模具钢、合金钢
'材料类别' = 1
'圆钢材料组' = 2
'方钢材料组' = 3
# 管子、炮筒
'模套分类' = 4
# 冷作、热作
'制作方式' = 5
# 进口、国标
'制作标准' = 6
# 淬火、未淬火
'处理工艺' = 7
'产地' = 8
