[mysql]
host = 'localhost'
user = 'root'
password = ''
database = 'toy-box'

[sign]
# 出入库
type1 = 0
# 材料类别
# 圆钢、方钢、模套、模具钢、合金钢
type2 = 1
# 圆钢材料组
type3 = 2
# 方钢材料组
type4 = 3
# 模套分类
# 管子、炮筒
type5 = 4
# 制作方式
# 冷作、热作
type6 = 5
# 制作标准
# 进口、国标
type7 = 6
# 处理工艺
# 淬火、未淬火
type8 = 7
# 产地
type9 = 8
