[goods-in]
sql = """
  insert into `goods_in_and_out` (type, length, width, height, weight, patch, material_cost, freight, material_type)
  values (@type, @length, @width, @height, @weight, @patch, @materialCost, @freight, @materialType)
"""
method = 'post'

[get-detail]
sql = """
  select * from material_detail where 类别 = @materialType
"""

[get-material-type]
sql = """
  select text, value from dictionary where sign = @sign
"""
