[goods-in]
sql = """
  insert into `goods_in_and_out` (type, height, weight, patch, material_cost, freight, description, extra_cost, material_id)
  values (@type, @height, @weight, @@dateStamp, @materialCost, @freight, @description, @extraCost, @materialId);

  update `material_detail` set 库存长度 = @newLength, 库存重量 = @newWeight, 单价 = @materialCost
  where id = @materialId;
"""
method = 'post'

[get-detail-by-material-id]
sql = """
  select * from material_detail where id = @materialId
"""
method = 'get'

[get-detail]
sql = """
  select * from material_detail where 类别 = @materialType
"""

[get-material-type]
sql = """
  select text, value from dictionary where sign = @sign
"""
