[goods-in]
sql = """
  insert into `goods_in_and_out` (type, height, weight, patch, material_cost, freight, description, extra_cost, material_id)
  values (@type, @height, @weight, @@dateStamp, @materialCost, @freight, @description, @extraCost, @materialId);

  update `material_detail` set 库存长度 = @newLength, 库存重量 = @newWeight, 单价 = @materialCost
  where id = @materialId;
"""
method = 'post'

[add-material-type]
sql = """
  insert into `material_detail` (类别, 材质, 单价, 锯费, 长, 宽, 高, 卖出方式, 圆钢种类, 制作标准, 制作方式)
  values (@类别, @材质, @单价, @锯费, @长, @宽, @高, @卖出方式, @圆钢种类, @制作标准, @制作方式)
"""
method = 'post'

[get-material-type-by-detail]
sql = """
  select * from `material_detail`
  where 长 = @长 and 宽 = @宽 and 高 = @高 and 类别 = @类别 and 材质 = @材质 and 卖出方式 = @卖出方式 and 圆钢种类 = @圆钢种类 and 制作标准 = @制作标准 and 制作方式 = @制作方式
"""
method = 'get'

[get-detail-by-material-id]
sql = """
  select * from material_detail where id = @materialId
"""
method = 'get'

[get-detail]
sql = """
  select * from material_detail where 类别 = @materialType
"""

[get-material-type]
sql = """
  select text, value from dictionary where sign = @sign
"""
