name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install --legacy-peer-deps

      - name: build
        run: npm run build:gh-pages

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./dist
          allow_empty_commit: false
          user_name: 'peko-bot'
          user_email: 'zy410419243+peko-bot@gmail.com'
