name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
      - name: compile
        run: npm run compile:server
      - name: build
        run: npm run build
      - name: test with reporting coverage
        run: npm run codecov
      - name: deploy to gh-pages
        run: npm run deploy
