name: site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: build for netlify
        run: npm run build

      - name: build for gh-pages
        run: npm run build:gh-pages
