name: ui-test

on: [push]

jobs:
  case:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm i -g argos-cli

      - name: test
        run: argos upload imgs --ignore **/*.diff.png --token ${{ secrets.ARGOS_TOKEN }} --branch=${{ github.ref }} --commit=${{ github.sha }}
