name: ui-test

on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: |
          npm i argos-cli
          git branch
          git checkout -b $(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$(jq .pull_request.number "$GITHUB_EVENT_PATH") | jq -r '.base.ref') origin $(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$(jq .pull_request.number "$GITHUB_EVENT_PATH") | jq -r '.base.ref')
          git branch

      - name: test
        run: |
          npm run argos -- --ignore **/*.diff.png --token=${{ secrets.ARGOS_TOKEN }} --branch=${{ github.event.pull_request.head.ref }} --commit=${{ github.sha }}
